### ISSUE TITLE
License Terms?

### ISSUE THREAD

**Issue by jrpretz** [kapadia/healpix.js#1]
I'm considering using this package in a webpage I'm developing to show high-energy maps of the sky. The data is in healpix and this library would useful in figuring out which area of the sky I'm looking at. 

I don't see a license. Can it be used?

**Comment by kapadia** [comment]
Sure, go for it: https://github.com/kapadia/healpix.js/commit/442d3721db8b45937824e35a2f3a3e8fb878e5e7

**Comment by jrpretz** [comment]
Thank you!
